version: "3"
services:
    app:
        image: made/made-app
        build: ./App
        ports:
            - "80:80"
        depends_on:
            server:
                condition: service_started
        restart: always
        # networks:
        #     pipe:
        #         ipv4_address: 192.168.4.69

    server:
        image: made/made-server
        build: ./Server
        ports:
            - "25565:25565"
        restart: always
        volumes:
            - ./Data:/MaDe/Data

        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
        #     interval: 5m
        #     timeout: 5s
        #     retries: 3
        #     start_period: 40s
        #     start_interval: 5s
        # networks:
        #     pipe:
        #         ipv4_address: 192.168.4.20

# networks:
#     pipe:
#         ipam:
#             driver: default
#             config:
#                 - subnet: "192.168.4.0/24"
