###

GET http://localhost:25565/instituti

###

get http://localhost:25565/sedi

###

GET http://localhost:25565/updateDB

###

get http://localhost:25565/institute/TNTD020009

###

get http://localhost:25565/sede/TNTD020009
